In [23]:
import pandas as pd 
import numpy as nd 
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

In [24]:
iris = load_iris()

In [25]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [26]:
def get_score(model, x_train, x_test, y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [27]:
from sklearn.model_selection import train_test_split,KFold,StratifiedKFold,cross_val_score

In [28]:
kf = KFold(n_splits=10)

In [29]:
ln = []
svm = []
rf = []
for train_index, test_index in kf.split(iris.data):
    x_train,x_test,y_train,y_test = iris.data[train_index],iris.data[test_index],iris.target[train_index],iris.target[test_index]
    ln.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

In [30]:
ln

[1.0,
 1.0,
 1.0,
 1.0,
 0.9333333333333333,
 0.8666666666666667,
 1.0,
 0.8666666666666667,
 0.8666666666666667,
 0.9333333333333333]

In [31]:
svm

[1.0,
 1.0,
 1.0,
 1.0,
 0.8666666666666667,
 0.8666666666666667,
 1.0,
 0.8666666666666667,
 0.8,
 0.9333333333333333]

In [32]:
rf

[1.0,
 1.0,
 1.0,
 1.0,
 0.9333333333333333,
 0.8666666666666667,
 1.0,
 0.8666666666666667,
 0.8,
 1.0]

In [33]:
folds = StratifiedKFold(n_splits=10)
ln = []
svm = []
rf = []
for train_index, test_index in kf.split(iris.data):
    x_train,x_test,y_train,y_test = iris.data[train_index],iris.data[test_index],iris.target[train_index],iris.target[test_index]
    ln.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

In [34]:
cross_val_score(LogisticRegression(max_iter=1000),iris.data,iris.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [35]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [36]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])